[package]
name = "grapple"
version = "0.1.0"
authors = ["Dave Allie <dave@daveallie.com>"]

[profile.release]
lto = true

[dependencies]
reqwest = "~0.4.0"
url = "~1.4.0"
rustc-serialize = "~0.3.0"
rust-crypto = "~0.2.0"
bytes = "~0.4.0"
lazy_static = "~0.2.0"
pbr = { git = "https://github.com/a8m/pb.git", rev = "e6e1fe6e4aa4e99c4594aa4943a42e91cfb41f90" }
clippy = {version = "*", optional = true}

[dependencies.clap]
version = "~2.20"
features = ["yaml"]

[dependencies.uuid]
version = "~0.4.0"
features = ["v4"]

[features]
default = []
