[package]
name = "grapple"
version = "0.1.0"
authors = ["Dave Allie <dave@daveallie.com>"]

[profile.release]
lto = true

[dependencies]
reqwest = "~0.4.0"
url = "~1.4.0"
rustc-serialize = "~0.3.0"
slog-term = "~1.3.0"
rust-crypto = "~0.2.0"
bytes = "~0.4.0"
clippy = {version = "*", optional = true}

[dependencies.clap]
version = "~2.20"
features = ["yaml"]

[dependencies.slog]
version = "~1.5"
default-features = false
features = ["release_max_level_debug", "max_level_trace"]

[dependencies.uuid]
version = "~0.4.0"
features = ["v4"]

[features]
default = []
